"""
ChArUco calibration board, configurable through the CALIBRATION.board block of the config.

The defaults reproduce Conv-ChArT's board (dcc/board.py): 5x5 squares, DICT_5X5_50, marker side 0.7 of
the square side, marker ids from 0, unitless square length 1.0.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import cv2
import numpy as np

_CFG_KEYS = {"squares", "square_length_m", "marker_length_m", "marker_ratio", "dictionary",
             "first_marker_id", "legacy_pattern"}


@dataclass(frozen=True)
class BoardSpec:
    """
    Physical ChArUco board.
      @args:
        squares: (cols, rows) of chessboard squares; rectangular boards are allowed.
        square_length: side of one square. Any unit works for K and dist; extrinsics come out in it.
        marker_length: side of one ArUco marker, same unit; None means marker_ratio * square_length.
        marker_ratio: marker side as a fraction of the square side, used when marker_length is None.
        dictionary: cv2.aruco predefined dictionary name, e.g. "DICT_5X5_50".
        first_marker_id: id of the board's first marker; the board uses consecutive ids from here.
        legacy_pattern: True for boards generated by OpenCV < 4.6 (matters for an even number of rows).
    """
    squares: tuple[int, int] = (5, 5)
    square_length: float = 1.0
    marker_length: float | None = None
    marker_ratio: float = 0.7
    dictionary: str = "DICT_5X5_50"
    first_marker_id: int = 0
    legacy_pattern: bool = False

    @property
    def marker_side(self) -> float:
        return self.marker_length if self.marker_length is not None else self.marker_ratio * self.square_length

    @property
    def n_inner_corners(self) -> int:
        cols, rows = self.squares
        return (cols - 1) * (rows - 1)


def board_spec_from_cfg(board_cfg: dict[str, Any] | None) -> BoardSpec:
    """
    Build a BoardSpec from a CALIBRATION.board mapping; missing or null keys keep the defaults.
      @args:
        board_cfg: keys squares, square_length_m, marker_length_m, marker_ratio, dictionary,
                   first_marker_id, legacy_pattern.
    """
    cfg = {k: v for k, v in (board_cfg or {}).items() if v is not None}
    unknown = set(cfg) - _CFG_KEYS
    if unknown:
        raise ValueError(f"unknown CALIBRATION.board keys: {sorted(unknown)}")
    default = BoardSpec()
    squares = tuple(int(v) for v in cfg.get("squares", default.squares))
    if len(squares) != 2:
        raise ValueError(f"CALIBRATION.board.squares must be [cols, rows], got {cfg['squares']}")
    return BoardSpec(
        squares=squares,
        square_length=float(cfg.get("square_length_m", default.square_length)),
        marker_length=float(cfg["marker_length_m"]) if "marker_length_m" in cfg else None,
        marker_ratio=float(cfg.get("marker_ratio", default.marker_ratio)),
        dictionary=str(cfg.get("dictionary", default.dictionary)),
        first_marker_id=int(cfg.get("first_marker_id", default.first_marker_id)),
        legacy_pattern=bool(cfg.get("legacy_pattern", default.legacy_pattern)),
    )


def make_board(spec: BoardSpec) -> cv2.aruco.CharucoBoard:
    """
    Build the cv2 CharucoBoard for spec, validating it against its dictionary.
    """
    cols, rows = spec.squares
    if cols < 2 or rows < 2:
        raise ValueError(f"a ChArUco board needs at least 2x2 squares, got {spec.squares}")
    if not 0.0 < spec.marker_side < spec.square_length:
        raise ValueError(f"marker side {spec.marker_side} must be positive and smaller than the square "
                         f"side {spec.square_length}")
    if not spec.dictionary.startswith("DICT_") or not hasattr(cv2.aruco, spec.dictionary):
        raise ValueError(f"unknown cv2.aruco dictionary {spec.dictionary!r}")
    dictionary = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, spec.dictionary))
    probe = cv2.aruco.CharucoBoard((cols, rows), spec.square_length, spec.marker_side, dictionary)
    n_markers = len(probe.getIds())
    capacity = dictionary.bytesList.shape[0]
    if spec.first_marker_id < 0 or spec.first_marker_id + n_markers > capacity:
        raise ValueError(f"markers {spec.first_marker_id}..{spec.first_marker_id + n_markers - 1} do not fit "
                         f"{spec.dictionary} ({capacity} markers)")
    ids = np.arange(spec.first_marker_id, spec.first_marker_id + n_markers, dtype=np.int32)
    board = cv2.aruco.CharucoBoard((cols, rows), spec.square_length, spec.marker_side, dictionary, ids)
    board.setLegacyPattern(spec.legacy_pattern)
    return board
